from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from io import BytesIO

def generate_invoice_pdf(invoice):
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    y = height - 50
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(50, y, "INVOICE")

    # Invoice Number & Date
    y -= 40
    pdf.setFont("Helvetica", 10)
    pdf.drawString(50, y, f"Invoice Number: {invoice.invoice_number}")
    pdf.drawString(250, y, f"Date: {invoice.created_at.strftime('%Y-%m-%d')}")

    # Shop & Generated By
    y -= 20
    pdf.drawString(50, y, f"Shop: {invoice.shop.name}")
    y -= 15
    pdf.drawString(50, y, f"Generated by: {invoice.created_by.username}")

    # Payment Info
    y -= 20
    pdf.drawString(50, y, f"Payment Method: {invoice.payment_method or 'Not specified'}")
    pdf.drawString(250, y, f"Payment Status: {invoice.payment_status or 'Pending'}")

    # Customer Info
    y -= 30
    pdf.drawString(50, y, f"Customer: {invoice.customer_name}")
    if invoice.customer_email:
        y -= 15
        pdf.drawString(50, y, f"Email: {invoice.customer_email}")

    # Items Table Header
    y -= 40
    pdf.drawString(50, y, "Items:")
    y -= 20
    pdf.drawString(50, y, "Product")
    pdf.drawString(250, y, "Qty")
    pdf.drawString(300, y, "Price")
    pdf.drawString(380, y, "Total")

    y -= 15
    pdf.line(50, y, 500, y)

    # Items
    for item in invoice.items:
        y -= 20
        pdf.drawString(50, y, item.product.name)
        pdf.drawString(250, y, str(item.quantity))
        pdf.drawString(300, y, f"{item.price:.2f}")
        pdf.drawString(380, y, f"{item.total_price:.2f}")

    # Totals Section
    y -= 40
    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(300, y, f"Sub Total: {invoice.sub_total:.2f}")

    y -= 15
    pdf.drawString(300, y, f"Tax ({invoice.tax_rate}%): {invoice.tax_amount:.2f}")

    y -= 15
    pdf.drawString(300, y, f"Discount: {invoice.discount_amount:.2f}")

    y -= 20
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(300, y, f"Grand Total: {invoice.grand_total:.2f}")

    pdf.showPage()
    pdf.save()

    buffer.seek(0)
    return buffer
